language: csharp
dist: trusty
mono: none 
dotnet: 2.0.0
script:
 - cd ./src/SimpleCQRS
 - dotnet restore SimpleCQRS.sln && dotnet build SimpleCQRS.sln

#  env:
#   global:
#     - "FTP_USER=user"
#     - "FTP_PASSWORD=password"
# after_success:
#     "curl --ftp-create-dirs -T uploadfilename -u $FTP_USER:$FTP_PASSWORD ftp://sitename.com/directory/myfile"
