language: csharp
dist: trusty
mono: none 
dotnet: 2.0.0
script:
 - npm install -g webpack
# - cd src/SimpleCQRS
 - dotnet restore SimpleCQRS.sln && dotnet build SimpleCQRS.sln
# - cd wwwroot/react-app/
# - npm i -g npm to update 
# - npm install && npm run build

#  env:
#   global:
#     - "FTP_USER=user"
#     - "FTP_PASSWORD=password"
# after_success:
#     "curl --ftp-create-dirs -T uploadfilename -u $FTP_USER:$FTP_PASSWORD ftp://sitename.com/directory/myfile"
